### ISSUE TITLE
Data vanishes when resizing tables to larger than their initial size

### ISSUE THREAD

**Issue by jrhe** [Addepar/ember-table#161]
Data vanishes when resizing tables to larger than their initial size. This is with no extra styles or customisation.

I managed to fix it with the following css but I'm not sure what repercussions it might have:

``` css
.ember-table-table-block {
  position: static !important;
}
```
