### ISSUE TITLE
[Alpha] - Flexbox issue with Firefox

### ISSUE THREAD

**Issue by gwak** [Addepar/ember-table#450]
There seem to be an issue with Firefox and Flexbox layout within a table element.
The `.et-tbody-container` div element should overflow vertical content which it does well in Chrome thanks to : 
```css
.et-table .et-tbody-container {
  overflow-y: scroll;
  flex: 1;
}  
```
But in Firefox the tbody content is not overflowed thus making the table impossible to scroll. It seems that the `overflow-y: scroll` isn't taken into account if `.et-tbody-container` has a flex layout.

The only way I found to make the content of `.et-tbody-container` scroll is by setting a fixed height and removing the flex layout:
 
```css
.et-table .et-tbody-container {
  overflow-y: scroll;
  height: 600px;
}  
```

**Comment by gwak** [comment]
Ok, I think I found what my problem was, so for future reference, here's a fix. 
I need to make sure that container div that holds the `table.et-table` has the following style:
```css
.table-container {
  display: flex;
  flex: 1;
  flex-direction: column;
  min-height: 100%;
}
```

The important bit is **`min-height: 100%;`** .
